# Generated by Django 5.1.3 on 2025-01-10 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0004_product_for_training_product_reverse_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('postcode', models.CharField(max_length=10)),
                ('town_or_city', models.CharField(blank=True, max_length=30, null=True)),
                ('address_line_one', models.CharField(blank=True, max_length=50, null=True)),
                ('address_line_two', models.CharField(blank=True, max_length=50, null=True)),
                ('county', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('order_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regular_size', models.CharField(blank=True, max_length=2, null=True)),
                ('fin_size', models.CharField(blank=True, max_length=4, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('item_total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checkout.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
    ]
