# Generated by Django 5.1.3 on 2025-02-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='regular_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
