# Generated by Django 5.1.3 on 2025-01-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_is_personalised'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='for_training',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='reverse_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='reverse_image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
