# Generated by Django 5.1.3 on 2025-01-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_subcategory_product_subcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='name',
            field=models.CharField(default='Unnamed Subcategory', max_length=254),
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategories',
        ),
        migrations.AddField(
            model_name='product',
            name='subcategories',
            field=models.ManyToManyField(blank=True, to='home.subcategory'),
        ),
    ]
